name: CI

on:
    push:
        paths-ignore:
            - "*.md"
    pull_request:
        branches: [$default-branch]
    schedule:
        - cron: "0 12 * * 0"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    tests:
        name: Tests
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                node-version: [16, 18]
                os: [ubuntu-latest, windows-latest]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "npm"

            - name: Install
              run: npm ci

            - name: Run coverage
              run: npm run coverage
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Install
              run: npm ci

            - name: Run tests
              run: npm run test

    coverage:
        name: Coverage
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "npm"

            - name: Install
              run: npm ci

            - name: Run coverage
              run: npm run coverage
